Added - Preview + Link if the data is too long. Removed - Asterisks from Example
z64/discord-against-humanity pull request #23
Opened 2016-11-28 17:30 UTC by Cyan101

2016-11-28 18:06 UTC, z64 requested changes

2016-11-28 18:06 UTC, z64 commented on README.md
> +![logo](http://i.imgur.com/2R6gSEV.png)
In the future, please keep unrelated changes to separate PR's.

2016-11-28 18:06 UTC, z64 commented on src/modules/commands/urban.rb
> +            value: "*#{word.long? ? word.example.gsub('*','')[0..600].strip + '...' : word.example.gsub('*','')}*", inline: false if word.example
Both of these interpolations are now doing too much work, making this difficult to read (performing these operations has nothing to do with presenting the embed field). This should be abstracted into a helper method, perhaps similar to how I patched in `#long?`, but perhaps not, as this is a hack to begin with.

Beyond this, we should show as much of the definition as possible, not just 600 characters. We know exactly how long the markdown link will be, so you can come up with a way to replace exactly that amount off of the end.

If I were writing this, I would make the markdown link a template ;

```ruby
READ_MORE = ' ...(Read More)](url)'
```

and then generate the markdown replacement with the url like:

```ruby
url = READ_MORE.gsub 'url', word.url
text = word.text[0..-url.length].strip + url
```

which can then be suitably presented in the interpolation inside the embed.

2016-11-30 09:01 UTC, Cyan101 commented
Commited some changes

2016-12-01 09:29 UTC, z64 requested changes

2016-12-01 09:29 UTC, z64 commented on src/modules/commands/urban.rb
> +                      value: word.long_text? ? truncate(word.text, url) : word.text, inline: false
don't split the lines here, its inconsistent with the rest of the file. one line is fine

2016-12-01 09:29 UTC, z64 commented on src/modules/commands/urban.rb
> +          e.color = 5_800_090
Revert this

2016-12-01 09:43 UTC, z64 approved these changes

2016-12-01 10:14 UTC, Cyan101 commented
Good stuff :)

2017-04-10 14:24 UTC, merged